var Global={domain:function(){var a;var b=location.host;a=1;if(!b||1>a)a="";else{var c={com:1,net:1,org:1,gov:1,edu:1,mil:1,biz:1,name:1,info:1,mobi:1,pro:1,travel:1,museum:1,"int":1,areo:1,post:1,rec:1,cn:1},d=b.split(".");if(1>=d.length||!isNaN(d[d.length-1]))a=b;else{for(var b=d.length-1,e="";0<b&&0<a;)e="."+d[b]+e,c[d[b]]&&1===c[d[b]]||a--,b--;a=e}}return a.toLowerCase()}(),setCookie:function(){if(!document.cookie)return!1;var a=new Date;2<arguments.length?a.setTime(a.getTime()+864E5*arguments[2]):
a.setTime(a.getTime()+18E5);2<=arguments.length&&(document.cookie=arguments[0]+"="+escape(arguments[1])+"; expires="+a.toGMTString()+"; domain="+Global.domain+"; path=/")},getCookie:function(a){var b;return(b=document.cookie.match(RegExp("(^| )"+a+"=([^;]*)(;|$)")))?decodeURIComponent(b[2]):""},setLocalStorage:function(a,b){window.localStorage&&window.localStorage.setItem(a,b)},getLocalStorage:function(a){return window.localStorage?window.localStorage.getItem(a):""},setWinName:function(a,b){if(""===
window.name)window.name='{"'+a+'":"'+b+'"}';else{var c=eval("("+window.name+")");c[a]=b;JSON&&"function"===typeof JSON.stringify&&(window.name=JSON.stringify(c))}},getWinName:function(a){if(""===window.name)return"";var b=eval("("+window.name+")");return b[a]?b[a]:""},getUUID:function(a){var b="xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;return("x"==a?b:b&3|8).toString(16)}),b=Global.getCookie(a)||Global.getLocalStorage(a)||Global.getWinName(a)||b;Global.setCookie(a,
b,365);Global.setLocalStorage(a,b);Global.setWinName(a,b);return b}};String.prototype.trim=function(){return this.replace(/^\s\s*/,"").replace(/\s\s*$/,"")};window.sentlog=window.sentlog||{referrer:!1};window.site_name=window.site_name||"58";var json_trackPagetype="NA",json_trackURL="NA",json_trackParams="NA",json_trackPageview="NA",json_sid="NA";
"undefined"!=typeof ____json4fe&&("_trackPagetype"in ____json4fe&&(json_trackPagetype=____json4fe._trackPagetype),"_trackURL"in ____json4fe&&(json_trackURL=____json4fe._trackURL),"_trackParams"in ____json4fe&&(json_trackParams=____json4fe._trackParams),"_trackPageview"in ____json4fe&&(json_trackPageview=____json4fe._trackPageview),"sid"in ____json4fe&&(json_sid=____json4fe.sid));window.tgreg=window.tgreg||-1;window._trackURL=window._trackURL||json_trackURL||"NA";
window._trackParams=window._trackParams||json_trackParams||"NA";var referrer=encodeURIComponent(document.referrer),pagetypeTmp,post_countTmp,cateTmp="",areaTmp="",GA_pageviewTmp="",ROITmp="";
if("NA"!=_trackURL){var trackJsonStr=eval("("+_trackURL+")");trackJsonStr.pagetype&&(pagetypeTmp=trackJsonStr.pagetype);trackJsonStr.post_count&&(post_countTmp=trackJsonStr.post_count);trackJsonStr.cate&&(cateTmp=trackJsonStr.cate);trackJsonStr.area&&(areaTmp=trackJsonStr.area);trackJsonStr.GA_pageview&&(GA_pageviewTmp=trackJsonStr.GA_pageview);trackJsonStr.ROI&&(ROITmp=trackJsonStr.ROI)}window.page_type=window.page_type||pagetypeTmp||json_trackPagetype||"NA";
window.post_count=window.post_count||post_countTmp||-1;window._gaq=window._gaq||[];var GTID=Math.random(),GTID=(new Date).valueOf()+""+GTID;"NA"!=json_sid&&""!=json_sid&&(GTID=json_sid);var ClickID=1,curURL=window.location.href;insertIntoTrackURL("GTID",GTID);
if(window.$){(function(){-1!=(_trackURL||"NA").indexOf("'pagetype':'home'")&&$("[href]").bind("click",function(a){var b=$(this).attr("href"),c=$(this).offset().top,d=$(this).offset().left,e=a.pageX;a=a.pageY;clickLog("from=heatmap:"+encodeURIComponent(b)+"&tagX="+d+"&tagY="+c+"&mouseX="+e+"&mouseY="+a)})})();(function(){$("[tongji_id]").bind("click",function(a){var b=a.srcElement?a.srcElement:a.target;"A"==b.tagName.toUpperCase()&&(a=$(b).attr("href")||"#",b=$(b).text(),-1==a.indexOf("javascript:")&&
"#"!=a.substring(0,1)&&clickLog("from="+$(this).attr("tongji_id")+"&text="+encodeURIComponent(b)+"&to="+encodeURIComponent(a)+"&tongji_type=tongji_id"))})})();(function(){$("[tongji_tag]").bind("click",function(){var a=$(this).attr("tongji_tag"),b=$(this).text().trim();clickLog("from="+a+"&text="+encodeURIComponent(b)+"&tongji_type=tongji_tag")})})();try{$("#zp_recommend").delegate&&$("#zp_recommend").delegate("a","click",function(){var a=ClickID;if("NO"==filterList(curURL)&&-1!=curURL.indexOf(".58.com")){var b=
$(this).attr("href")||"#";-1!=b.indexOf("javascript:")||"#"==b.substring(0,1)||"NO"!=filterList(b)||"/"!=b.substring(0,1)&&-1==b.indexOf(".58.com")||(b.match(/[\?&]ClickID=\d*/)?$(this).attr("href",b.replace(/ClickID=\d*/,"ClickID="+a)):$(this).attr("href",b.trim()+(-1==b.indexOf("?")?"?":"&")+"PGTID="+GTID+"&ClickID="+a))}})}catch(e$$14){}$("a").bind("click",function(){var a=ClickID;if("NO"==filterList(curURL)&&-1!=curURL.indexOf(".58.com")){var b=$(this).attr("href")||"#";-1!=b.indexOf("javascript:")||
"#"==b.substring(0,1)||"NO"!=filterList(b)||"/"!=b.substring(0,1)&&-1==b.indexOf(".58.com")||(b.match(/[\?&]ClickID=\d*/)?$(this).attr("href",b.replace(/ClickID=\d*/,"ClickID="+a)):$(this).attr("href",b.trim()+(-1==b.indexOf("?")?"?":"&")+"PGTID="+GTID+"&ClickID="+a))}})}
if(-1!=curURL.indexOf("post.58.com")||!sentlog.referrer){_trackParams=format_trackParams(_trackParams);_trackParams=encodeURIComponent(_trackParams);var logmsg="tag=pvstatall&referrer="+referrer+"&type="+page_type+"&post_count="+post_count+"&_trackParams="+_trackParams;if("detail"==page_type||"jianli_detail"==page_type)try{logmsg=logmsg+"&userid="+____json4fe.userid;"phone"in ____json4fe&&(logmsg=logmsg+"&huzhuan="+____json4fe.phone);0<tgreg&&(logmsg=logmsg+"&tgreg="+tgreg);if("infoid"in ____json4fe){var infoid=
____json4fe.infoid;insertIntoTrackURL("infoid",infoid)}if(curURL.match(/[\?&]iuType=[a-z]*_[0-9]*/)){var iType=curURL.match(/[\?&]iuType=[a-z]*_[0-9]*/)[0].split("=")[1].split("_")[0],uType=curURL.match(/[\?&]iuType=[a-z]*_[0-9]*/)[0].split("=")[1].split("_")[1];insertIntoTrackURL("infotype",iType);insertIntoTrackURL("usertype",uType)}}catch(e$$15){}try{if("version"in ____json4fe&&(logmsg=logmsg+"&version="+____json4fe.version),"smsc"in ____json4fe&&(logmsg=logmsg+"&smsc="+____json4fe.smsc),"start"in
____json4fe&&(logmsg+="&loadtime="+((new Date).getTime()-____json4fe.start)),"supplycount"in ____json4fe)for(var attr in ____json4fe.supplycount)logmsg=logmsg+"&supplycount."+attr+"="+____json4fe.supplycount[attr]}catch(e$$16){}try{logmsg=logmsg+"&window_size="+document.documentElement.clientWidth+"x"+document.documentElement.clientHeight}catch(e$$17){}try{var cookie_als=getcookie("als")||"";cookie_als&&""!=cookie_als&&insertIntoTrackURL("als",cookie_als);var cookie_utm_source=getcookie("utm_source")||
"",cookie_utm_campaign=getcookie("utm_campaign")||"",cookie_spm=getcookie("spm")||"";insertIntoTrackURL("utm_source",cookie_utm_source);logmsg=logmsg+"&utm_source="+cookie_utm_source;insertIntoTrackURL("utm_campaign",cookie_utm_campaign);insertIntoTrackURL("spm",cookie_spm);var cookie_platform=getcookie("f")||"";insertIntoTrackURL("tag_tmp",cookie_platform);var init_refer=referrer,cookie_init_refer=getcookie("init_refer"),cookie_new_session=getcookie("new_session");cookie_new_session&&""!=cookie_new_session?
(setcookie_session("new_session","0"),setcookie_session("init_refer",cookie_init_refer),insertIntoTrackURL("init_refer",cookie_init_refer),insertIntoTrackURL("new_session","0")):(setcookie_session("new_session","1"),setcookie_session("init_refer",init_refer),insertIntoTrackURL("init_refer",init_refer),insertIntoTrackURL("new_session","1"));var cookie_new_uv=getcookie("new_uv");cookie_new_uv&&""!=cookie_new_uv?cookie_new_session&&""!=cookie_new_session||cookie_new_uv++:cookie_new_uv=1;setcookie("new_uv",
cookie_new_uv,365);insertIntoTrackURL("new_uv",cookie_new_uv);logmsg=logmsg+"&_ga_utma=1.1.1.1.1."+cookie_new_uv;insertIntoTrackURL("uuid",Global.getUUID())}catch(e$$18){}"NA"!=_trackURL&&(logmsg=logmsg+"&trackURL="+_trackURL);ajaxlog_new(logmsg);"NA"!=_trackURL&&"NA"!=pagetypeTmp&&"list"==pagetypeTmp&&ajaxlog_pclistshow(_trackURL);sentlog.referrer=!0}
function setcookie(a,b,c){var d=new Date;d.setTime(d.getTime()+864E5*c);document.cookie=a+"="+escape(b)+"; expires="+d.toGMTString()+"; domain=.58.com; path=/"}function setcookie_session(a,b){var c=new Date;c.setTime(c.getTime()+18E5);document.cookie=a+"="+escape(b)+"; expires="+c.toGMTString()+"; domain=.58.com; path=/"}function getcookie(a){var b;return(b=document.cookie.match(RegExp("(^| )"+a+"=([^;]*)(;|$)")))?unescape(b[2]):""}function ajaxsend(a){(new Image).src=a}
function ajaxlog(a){ajaxsend(document.location.protocol+"//track.58.com/empty.js.gif?site_name="+site_name+"&"+a+"&rand="+Math.random());ajaxsend(document.location.protocol+"//tracklog1.58.com/pc/empty.js.gif?site_name="+site_name+"&"+a+"&rand="+Math.random())}
function ajaxlog_new(a){var b=Math.random();ajaxsend(document.location.protocol+"//tracklog1.58.com/pc/empty.js.gif?fromid=referrer4&site_name="+site_name+"&"+a+"&rand_id="+b);var c=_trackURL||"NA";if("job"==ROITmp||"detail"==page_type||"jianli_detail"==page_type)"job"!=ROITmp&&-1==c.indexOf("'cate':'9224")&&-1==c.indexOf("'cate':'9225")&&-1==c.indexOf("'cate':'13941")&&-1==c.indexOf("'cate':'13952")||ajaxsend(document.location.protocol+"//dialog.58.com/transfer?DIATag=PCTrack&"+a+"&rand_id="+b);
"list"==pagetypeTmp&&(a=GA_pageviewTmp.indexOf("?key="),b="",-1!=a&&(b=GA_pageviewTmp.substring(a+5)),ajaxsend(document.location.protocol+"//gdt.cm.58.com/gdtcm?city="+areaTmp+"&cate="+cateTmp+"&key="+b+"&plat=PC"))}function ajaxlog2(a){ajaxlog(a)}function ajaxlogr(a){ajaxsend(document.location.protocol+"//tracklog1.58.com/pc/click/listclicklog?site_name="+site_name+"&"+a+"&trackURL="+_trackURL+"&ClickID="+ClickID+"&referrer="+referrer+"&rand="+Math.random());setTimeout("ClickIDPlus()",300)}
function format_trackParams(a){if("NA"==a)return a;try{for(var b=[],c=0,d=a.length;c<d;c++)b.push(a[c].I+":"+a[c].V.replace(/\|/g,"*"));return b.join("@@")}catch(e){return"error"}}
function clickLog(a){var b=getcookie("bangbangid");b&&""!=b||(b="");var c=ClickID;ajaxsend(document.location.protocol+"//tracklog1.58.com/pc/click/empty.js.gif?site_name="+site_name+"&tag=pvsiters&"+a+"&trackURL="+_trackURL+"&ClickID="+c+"&bangbangid="+b+"&referrer="+referrer+"&rand="+Math.random());"job"!=ROITmp&&-1==a.indexOf("&ROI=")||ajaxsend(document.location.protocol+"//dialog.58.com/transfer?DIATag=PCClick&"+a+"&trackURL="+_trackURL+"&ClickID="+c+"&bangbangid="+b+"&referrer="+referrer+"&rand="+
Math.random());setTimeout("ClickIDPlus()",300)}function ClickIDPlus(){ClickID+=1}function showLog(a){var b=getcookie("bangbangid");b&&""!=b||(b="");ajaxsend(document.location.protocol+"//dialog.58.com/transfer?DIATag=PCTuijianShow&"+a+"&trackURL="+_trackURL+"&bangbangid="+b+"&referrer="+referrer+"&rand="+Math.random())}
function filterList(a){var b=".58.com.cn portal.58.com faw-vw-dasweltauto.58.com 5858.com lieche.58.com dict.58.com/xiaoqu about.58.com".split(" "),c;for(c in b)if(-1!=a.indexOf(b[c]))return"YES";return"NO"}function insertIntoTrackURL(a,b){if(a){var c=_trackURL;try{if("NA"!=_trackURL&&-1!=_trackURL.indexOf("{")){var d=_trackURL.indexOf("{");_trackURL=_trackURL.substring(0,d+1)+"'"+a+"':'"+b+"',"+_trackURL.substring(d+1)}else _trackURL="{'"+a+"':'"+b+"'}"}catch(e){_trackURL=c}}}
function ajaxlog_pclistshow(a){try{if(window.$){var b=getcookie("bangbangid");b&&""!=b||(b="");var c=Math.random();data_arr=[];"NA"!=cateTmp&&cateTmp.split(",");for(var d=$("[logr]"),e=0,f=d.length;e<f;e++)if($(d[e]).attr("logr")){var h=[],g="",k=$(d[e]).attr("logr").split("_");h.push(k[0],k[1],k[2],k[3]);var m=$(d[e]).attr("_pos"),l=e+1,p=$(d[e]).attr("sortid"),q=$(d[e]).attr("infoproperty"),n=k[k.length-1];n&&-1!=n.indexOf("ses^")&&(n=n.replace("ses^","ses:"),g+=n);p&&(g+="@sortid:"+p);l&&(g+="@pos:"+
l);m&&(g+="@npos:"+m);q&&(g+="@infoproperty:"+q);""!=g&&h.push(g);data_arr.push(h.join("_"))}ajaxsend(document.location.protocol+"//tracklog1.58.com/PCv1/listshow/empty.js.gif?tag=pclistshow&fromid=referrer4&bangbangid="+b+"&referrer="+referrer+"&site_name="+site_name+"&info_data="+data_arr.join(",")+"&trackURL="+a+"&rand_id="+c)}}catch(r){ajaxsend(document.location.protocol+"//tracklog1.58.com/PCv1/listshow/empty.js.gif?tag=pclistshow&fromid=referrer4&Error="+r)}}
function listclicklog(){var a=getcookie("bangbangid");a&&""!=a||(a="");var b="",c=ClickID,d=Math.random(),e=$(this).parents("[logr]"),b=[],f="",h=e.attr("logr").split("_");b.push(h[0],h[1],h[2],h[3]);var g=e.attr("_pos"),k=$("[logr]").index(e)+1,m=e.attr("sortid"),e=e.attr("infoproperty"),l=h[h.length-1];l&&-1!=l.indexOf("ses^")&&(l=l.replace("ses^","ses:"),f+=l);m&&(f+="@sortid:"+m);k&&(f+="@pos:"+k);g&&(f+="@npos:"+g);e&&(f+="@infoproperty:"+e);""!=f&&b.push(f);b=b.join("_");"NO"==filterList(curURL)&&
-1!=curURL.indexOf(".58.com")&&(f=$(this).attr("href")||"#",-1!=f.indexOf("javascript:")||"#"==f.substring(0,1)||"NO"!=filterList(f)||"/"!=f.substring(0,1)&&-1==f.indexOf(".58.com")||f.match(/[\?&]iuType=/)||$(this).attr("href",f.trim()+(-1==f.indexOf("?")?"?":"&")+"iuType="+h[0]+"_"+h[1]));ajaxsend(document.location.protocol+"//tracklog1.58.com/PCv1/listclick/empty.js.gif?tag=pclistclick&fromid=referrer4&bangbangid="+a+"&referrer="+referrer+"&site_name="+site_name+"&info_data="+b+"&trackURL="+_trackURL+
"&ClickID="+c+"&rand_id="+d);setTimeout("ClickIDPlus()",300)}function filterPagetype_normal(a){var b=["list","jianli_list","xiaoqu","qijiandian","item"];b[4]="xinchong";for(var c in b)if(a==b[c])return"YES";return"NO"}
if(window.$)try{(function(){if("NA"!=_trackURL&&"NA"!=page_type){var a=page_type.trim();if("YES"==filterPagetype_normal(a)){$("[logr] a.t").bind("click",listclicklog);var b=a="";"NA"!=cateTmp?(a=cateTmp.split(",")[0],b=cateTmp.split(",")[1]):a="";"1"==a&&"12"==b?($("[logr] a.jjh_img").bind("click",listclicklog),$("[logr] .img a").bind("click",listclicklog)):"187"==a||"42270"==a?$("[logr]").find("a:first").bind("click",listclicklog):"9225"==a||"13952"==a?$("[logr] a.fl").bind("click",listclicklog):
$("[logr] .img a").bind("click",listclicklog)}else"chexing"==a&&($("[logr] a.at").bind("click",listclicklog),$("[logr] .tdimg a").bind("click",listclicklog))}})()}catch(e$$22){ajaxsend(document.location.protocol+"//tracklog1.58.com/PCv1/listclick/empty.js.gif?tag=pclistclick&fromid=referrer4&Error="+e$$22)}var als=getcookie("als");if((!als||""==als)&&window.$)$("body").one("mouseover",function(){setcookie("als","0",365)});var isSpider=getcookie("isSpider");
isSpider&&""!=isSpider&&setcookie("isSpider","",0);
